### ISSUE TITLE
openssl

### ISSUE THREAD

**Issue by wildflower34** [trailofbits/winchecksec#1044] opened 2022-04-17 19:54 UTC
When I try to build a project this error occurs. I checked the directory and the include file does exist. 
![image](https://user-images.githubusercontent.com/94256837/163730008-bf576d00-cca5-49c7-9228-f746d437a497.png)

**Comment by woodruffw** [comment] 2022-04-19 13:41
Winchecksec depends on [uthenticode](https://github.com/trailofbits/uthenticode), which in turn depends on OpenSSL. 

Did you follow the [building steps](https://github.com/trailofbits/winchecksec#building) listed in the README? Those steps will ensure that all dependencies and subdependencies are installed correctly.

**Comment by woodruffw** [comment] 2022-08-10 14:36
Closing as invalid. I confirmed that the build steps in the README are functioning as intended.

**Closed by woodruffw** 2022-08-10 14:36 UTC
Labels: invalid
