### ISSUE TITLE
Show CET support

### ISSUE THREAD

**Issue by yardenshafir** [trailofbits/winchecksec#1047] opened 2022-10-27 13:33 UTC
Find the CET configuration of a file, added with the compilation flag /cetcompat.
This requires parsing a new debug directory entry `IMAGE_DEBUG_TYPE_EX_DLLCHARACTERISTICS` and check bit 0, indicating that the PE is compiled with /cetcompat.
The debug directory can be found through NtHeader.OptionalHeader.DataDirArray[DEBUG_DIRECTORY].VirtualAddress. Looks like at the moment pe-parser doesn't support parsing of debug directories so functionality will need to be added there first.

**Comment by woodruffw** [comment] 2022-10-27 14:03
Possibly a dupe of #44?

**Comment by yardenshafir** [comment] 2022-10-27 14:42
Seems like a dupe, my bad

**Comment by woodruffw** [comment] 2022-10-27 14:43
All good, just making sure I didn't miss something 🙂 

I agree we should prioritize this!

**Closed** 2022-10-27 14:43 UTC
Labels: enhancement
